### ISSUE TITLE
Eclim installer deletes $ECLIPSE_HOME/plugins/org.eclim_2.6.0/bin/eclimd and then expects it to be there

### ISSUE THREAD

**Issue by josiah14** [ervandew/eclim#517]
```
location was initialized.  Will retry after the state location is initialized.
2017-05-20 20:15:29,767 INFO  [ANT]      [exec] rm: cannot remove '/home/josiah/eclipse/java-neon2/eclipse/eclim': No such file or directory
2017-05-20 20:15:30,167 ERROR [ANT]      [exec] Result: 1
2017-05-20 20:15:30,172 INFO  [ANT]      [exec] rm: cannot remove '/home/josiah/eclipse/java-neon2/eclipse/eclimd': No such file or directory
2017-05-20 20:15:30,572 ERROR [ANT]      [exec] Result: 1
2017-05-20 20:15:30,626 INFO  [ANT]     [mkdir] Created dir: /tmp/formic_1899310961/update-site/plugins
2017-05-20 20:15:30,627 INFO  [ANT]     [mkdir] Created dir: /tmp/formic_1899310961/update-site/features
2017-05-20 20:15:30,648 INFO  [ANT] [eclim:unzip] Expanding: /tmp/eclim-update-site4711923109622149851.zip into /tmp/formic_1899310961/update-site
2017-05-20 20:15:30,811 INFO  [ANT] [formic:template] Evaluating template: /tmp/formic_1899310961/update-site/artifacts.xml
2017-05-20 20:15:30,817 INFO  [ANT] [formic:template] Moving 1 file to /tmp/formic_1899310961/update-site
2017-05-20 20:15:30,817 INFO  [ANT] [formic:template] Evaluating template: /tmp/formic_1899310961/update-site/content.xml
2017-05-20 20:15:30,821 INFO  [ANT] [formic:template] Moving 1 file to /tmp/formic_1899310961/update-site
2017-05-20 20:15:30,821 INFO  [ANT] [formic:template] Evaluating template: /tmp/formic_1899310961/update-site/features/org.eclim_2.6.0/feature.xml
2017-05-20 20:15:30,822 INFO  [ANT] [formic:template] Moving 1 file to /tmp/formic_1899310961/update-site/features/org.eclim_2.6.0
2017-05-20 20:15:30,839 INFO  [ANT]       [jar] Building jar: /tmp/formic_1899310961/update-site/artifacts.jar
2017-05-20 20:15:30,843 INFO  [ANT]    [delete] Deleting: /tmp/formic_1899310961/update-site/artifacts.xml
2017-05-20 20:15:30,846 INFO  [ANT]       [jar] Building jar: /tmp/formic_1899310961/update-site/content.jar
2017-05-20 20:15:30,847 INFO  [ANT]    [delete] Deleting: /tmp/formic_1899310961/update-site/content.xml
2017-05-20 20:15:30,851 INFO  [ANT]       [jar] Building jar: /tmp/formic_1899310961/update-site/features/org.eclim_2.6.0.jar
2017-05-20 20:15:30,856 INFO  [ANT]    [delete] Deleting directory /tmp/formic_1899310961/update-site/features/org.eclim_2.6.0
2017-05-20 20:15:30,860 INFO  [ANT]       [jar] Building jar: /tmp/formic_1899310961/update-site/plugins/org.eclim.adt_2.6.0.jar
2017-05-20 20:15:30,863 INFO  [ANT]    [delete] Deleting directory /tmp/formic_1899310961/update-site/plugins/org.eclim.adt_2.6.0
2017-05-20 20:15:30,866 INFO  [ANT]       [jar] Building jar: /tmp/formic_1899310961/update-site/plugins/org.eclim.core_2.6.0.jar
2017-05-20 20:15:30,909 INFO  [ANT]    [delete] Deleting directory /tmp/formic_1899310961/update-site/plugins/org.eclim.core_2.6.0
2017-05-20 20:15:30,915 INFO  [ANT]       [jar] Building jar: /tmp/formic_1899310961/update-site/plugins/org.eclim.jdt_2.6.0.jar
2017-05-20 20:15:31,030 INFO  [ANT]    [delete] Deleting directory /tmp/formic_1899310961/update-site/plugins/org.eclim.jdt_2.6.0
2017-05-20 20:15:31,036 INFO  [ANT]       [jar] Building jar: /tmp/formic_1899310961/update-site/plugins/org.eclim.vimplugin_2.6.0.jar
2017-05-20 20:15:31,043 INFO  [ANT]    [delete] Deleting directory /tmp/formic_1899310961/update-site/plugins/org.eclim.vimplugin_2.6.0
2017-05-20 20:15:31,047 INFO  [ANT]       [jar] Building jar: /tmp/formic_1899310961/update-site/plugins/org.eclim.wst_2.6.0.jar
2017-05-20 20:15:31,136 INFO  [ANT]    [delete] Deleting directory /tmp/formic_1899310961/update-site/plugins/org.eclim.wst_2.6.0
2017-05-20 20:15:31,142 INFO  [ANT]       [jar] Building jar: /tmp/formic_1899310961/update-site/plugins/org.eclim_2.6.0.jar
2017-05-20 20:15:31,373 INFO  [ANT]    [delete] Deleting directory /tmp/formic_1899310961/update-site/plugins/org.eclim_2.6.0
2017-05-20 20:15:31,376 INFO  [ANT] [eclim:installiu] Installing org.eclim...
2017-05-20 20:15:31,376 INFO  [org.formic.util.CommandExecutor] java -Xmx256m -jar /home/josiah/eclipse/java-neon2/eclipse/plugins/org.eclipse.equinox.launcher_1.3.201.v20161025-1711.jar -clean -application org.eclipse.equinox.p2.director -repository file:///tmp/formic_1899310961/update-site -installIU org.eclim.feature.group
2017-05-20 20:18:41,982 ERROR [ANT]
jar:file:/home/josiah/Downloads/eclim_2.6.0.jar!/installer.xml:231: Replace: source file /home/josiah/eclipse/java-neon2/eclipse/plugins/org.eclim_2.6.0/bin/eclimd doesn't exist
        at org.apache.tools.ant.taskdefs.Replace.processFile(Replace.java:663)
        at org.apache.tools.ant.taskdefs.Replace.execute(Replace.java:538)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
        at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
        at net.sf.antcontrib.logic.IfTask.execute(IfTask.java:217)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.TaskAdapter.execute(TaskAdapter.java:154)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
        at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:390)
        at org.apache.tools.ant.Target.performTasks(Target.java:411)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
        at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
        at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:458)
        at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:119)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
        at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:390)
        at org.apache.tools.ant.Target.performTasks(Target.java:411)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1368)
        at org.formic.wizard.step.shared.InstallAction.execute(InstallAction.java:124)
        at org.formic.wizard.step.gui.InstallStep$1.run(InstallStep.java:162)
        at foxtrot.AbstractWorkerThread$1.run(AbstractWorkerThread.java:40)
        at java.security.AccessController.doPrivileged(Native Method)
        at foxtrot.AbstractWorkerThread.runTask(AbstractWorkerThread.java:36)
        at foxtrot.workers.SingleWorkerThread.run(SingleWorkerThread.java:199)
        at foxtrot.workers.SingleWorkerThread.run(SingleWorkerThread.java:182)
        at java.lang.Thread.run(Thread.java:745)
2017-05-20 20:18:41,984 ERROR [ANT]
jar:file:/home/josiah/Downloads/eclim_2.6.0.jar!/installer.xml:146: The following error occurred while executing this line:
jar:file:/home/josiah/Downloads/eclim_2.6.0.jar!/installer.xml:231: Replace: source file /home/josiah/eclipse/java-neon2/eclipse/plugins/org.eclim_2.6.0/bin/eclimd doesn't exist
        at org.apache.tools.ant.ProjectHelper.addLocationToBuildException(ProjectHelper.java:551)
        at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:460)
        at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:119)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
        at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:390)
        at org.apache.tools.ant.Target.performTasks(Target.java:411)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1368)
        at org.formic.wizard.step.shared.InstallAction.execute(InstallAction.java:124)
        at org.formic.wizard.step.gui.InstallStep$1.run(InstallStep.java:162)
        at foxtrot.AbstractWorkerThread$1.run(AbstractWorkerThread.java:40)
        at java.security.AccessController.doPrivileged(Native Method)
        at foxtrot.AbstractWorkerThread.runTask(AbstractWorkerThread.java:36)
        at foxtrot.workers.SingleWorkerThread.run(SingleWorkerThread.java:199)
        at foxtrot.workers.SingleWorkerThread.run(SingleWorkerThread.java:182)
        at java.lang.Thread.run(Thread.java:745)
Caused by: jar:file:/home/josiah/Downloads/eclim_2.6.0.jar!/installer.xml:231: Replace: source file /home/josiah/eclipse/java-neon2/eclipse/plugins/org.eclim_2.6.0/bin/eclimd doesn't exist
        at org.apache.tools.ant.taskdefs.Replace.processFile(Replace.java:663)
        at org.apache.tools.ant.taskdefs.Replace.execute(Replace.java:538)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
        at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
        at net.sf.antcontrib.logic.IfTask.execute(IfTask.java:217)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.TaskAdapter.execute(TaskAdapter.java:154)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
        at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:390)
        at org.apache.tools.ant.Target.performTasks(Target.java:411)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
        at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
        at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:458)
        ... 19 more
jar:file:/home/josiah/Downloads/eclim_2.6.0.jar!/installer.xml:146: The following error occurred while executing this line:
jar:file:/home/josiah/Downloads/eclim_2.6.0.jar!/installer.xml:231: Replace: source file /home/josiah/eclipse/java-neon2/eclipse/plugins/org.eclim_2.6.0/bin/eclimd doesn't exist
        at org.apache.tools.ant.ProjectHelper.addLocationToBuildException(ProjectHelper.java:551)
        at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:460)
        at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:119)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
        at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:390)
        at org.apache.tools.ant.Target.performTasks(Target.java:411)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1368)
        at org.formic.wizard.step.shared.InstallAction.execute(InstallAction.java:124)
        at org.formic.wizard.step.gui.InstallStep$1.run(InstallStep.java:162)
        at foxtrot.AbstractWorkerThread$1.run(AbstractWorkerThread.java:40)
        at java.security.AccessController.doPrivileged(Native Method)
        at foxtrot.AbstractWorkerThread.runTask(AbstractWorkerThread.java:36)
        at foxtrot.workers.SingleWorkerThread.run(SingleWorkerThread.java:199)
        at foxtrot.workers.SingleWorkerThread.run(SingleWorkerThread.java:182)
        at java.lang.Thread.run(Thread.java:745)
Caused by: jar:file:/home/josiah/Downloads/eclim_2.6.0.jar!/installer.xml:231: Replace: source file /home/josiah/eclipse/java-neon2/eclipse/plugins/org.eclim_2.6.0/bin/eclimd doesn't exist
        at org.apache.tools.ant.taskdefs.Replace.processFile(Replace.java:663)
        at org.apache.tools.ant.taskdefs.Replace.execute(Replace.java:538)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
        at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
        at net.sf.antcontrib.logic.IfTask.execute(IfTask.java:217)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.TaskAdapter.execute(TaskAdapter.java:154)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
        at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:390)
        at org.apache.tools.ant.Target.performTasks(Target.java:411)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
        at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
        at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:458)
        ... 19 more
Installer Context (Please include in bug reports):
  eclipse.home=/home/josiah/eclipse/java-neon2/eclipse
  eclipse.info=org.eclim.installer.step.EclipseInfo@719f0e5d
  eclipse.local=/home/josiah/eclipse/java-neon2/eclipse
  eclipse.profile=_home_josiah_eclipse_java-neon2_eclipse
  featureList.adt=true
  featureList.cdt=false
  featureList.dltk=false
  featureList.dltkruby=false
  featureList.groovy=false
  featureList.jdt=true
  featureList.pdt=false
  featureList.pydev=false
  featureList.sdt=false
  featureList.wst=true
  vim.files=/home/josiah/.vim
  vim.skip=false

```
Never mind that `eclimd` would never be there, anyway, on a fresh install of Eclim, even if I create the plugins/org.eclim_2.6.0/bin directory immediately after the installer deletes it (I created a `watch -n 1` on the directory to monitor it), it still crashes because the eclimd file isn't there.

A possible workaround might be to run `mkdir -p org.eclim_2.6.0/bin && touch org.eclim_2.6.0/bin/eclimd` right after the installed finishes deleting the previous eclim installation, but I haven't tested that approach, yet.

**Comment by josiah14** [comment]
If I run the `touch` command to create the eclimd file, it crashes trying to find the next file it expects.  The installer will probably crash expecting everything to already be there in the `plugins` directory.  The only workaround would be to create a complete mock org.eclim_2.6.0 directory structure under plugins/, including files, and then see what happens.

It may be possible that the installer is looking in the wrong place for the Eclim plugin if these files should have been created by the installer.

```
jar:file:/home/josiah/Downloads/eclim_2.6.0.jar!/installer.xml:146: The following error occurred while executing this line:
jar:file:/home/josiah/Downloads/eclim_2.6.0.jar!/installer.xml:234: Replace: source file /home/josiah/eclipse/java-neon2/eclipse/plugins/org.eclim_2.6.0/bin/native/linux/eclimd.desktop doesn't exist
	at org.apache.tools.ant.ProjectHelper.addLocationToBuildException(ProjectHelper.java:551)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:460)
	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:119)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
	at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:390)
	at org.apache.tools.ant.Target.performTasks(Target.java:411)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1368)
	at org.formic.wizard.step.shared.InstallAction.execute(InstallAction.java:124)
	at org.formic.wizard.step.gui.InstallStep$1.run(InstallStep.java:162)
	at foxtrot.AbstractWorkerThread$1.run(AbstractWorkerThread.java:40)
	at java.security.AccessController.doPrivileged(Native Method)
	at foxtrot.AbstractWorkerThread.runTask(AbstractWorkerThread.java:36)
	at foxtrot.workers.SingleWorkerThread.run(SingleWorkerThread.java:199)
	at foxtrot.workers.SingleWorkerThread.run(SingleWorkerThread.java:182)
	at java.lang.Thread.run(Thread.java:745)
Caused by: jar:file:/home/josiah/Downloads/eclim_2.6.0.jar!/installer.xml:234: Replace: source file /home/josiah/eclipse/java-neon2/eclipse/plugins/org.eclim_2.6.0/bin/native/linux/eclimd.desktop doesn't exist
	at org.apache.tools.ant.taskdefs.Replace.processFile(Replace.java:663)
	at org.apache.tools.ant.taskdefs.Replace.execute(Replace.java:538)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
	at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
	at net.sf.antcontrib.logic.IfTask.execute(IfTask.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.TaskAdapter.execute(TaskAdapter.java:154)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
	at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:390)
	at org.apache.tools.ant.Target.performTasks(Target.java:411)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:458)
	... 19 more
```

**Comment by jguenther** [comment]
I'm having this exact same problem on MacOS El Capitan and java 1.8.0_60

**Comment by m5w** [comment]
I'm having this problem too on Kubuntu 16.04.2 with vim 8.0.0056 and Eclipse 4.6.3. Strangely, installing from the GUI works, but I get this error when I try to do an unattended install.

**Comment by rghamilton3** [comment]
I'm getting this with Ubuntu 14.04, Vim 8.0.636 and Eclipse 4.6.3 also

**Comment by mnp** [comment]
So does anyone have a workaround? This is basically a show stopper if you can't install.

**Comment by m5w** [comment]
Wait, are others not able to install at all? I've only ever encountered this bug when doing an unattended install.

**Comment by josiah14** [comment]
I have not found a way to get Eclim to install.

**Comment by rghamilton3** [comment]
Building from source SEEMS to work. I'll report back if I encounter any issues.

**Comment by josiah14** [comment]
@rghamilton3 I would expect building from source to work.  The problem appears to be that the installer, not Eclim itself, deletes the Eclim installation directory and then later on expects the directory it just deleted to be there.

**Comment by rghamilton3** [comment]
Oh yea well that's true. I guess what I should have said was in the mean time building from source is a workaround and probably easier than using the installer surprisingly.

**Comment by m5w** [comment]
I'll try an unattended install later tonight after building from source.

**Comment by rghamilton3** [comment]
Using the Eclipse tar package and not the installer, as mentioned on another issue, works as well. Neither of these are ideal solutions but they're something for now.

**Comment by rghamilton3** [comment]
@m5w Unattended install works for me using the tar package. Interestingly it never fails using the tar package but always does with the installer version

**Comment by mnp** [comment]
Both the GUI and the unattended installer are having the same issue.  OSX, Eclipse Neon, Java 1.8.0_92, Ant 1.9.7.  Script of unattended attached: [unattended.txt](https://github.com/ervandew/eclim/files/1128586/unattended.txt)

I'll try building from source.

**Comment by rghamilton3** [comment]
I tracked down the reason behind the error and it seems to have been fixed in the master branch.

**Comment by m5w** [comment]
An unattended install still doesn't work after building from source. Graphical installation still works fine.

**Comment by zhihuiFan** [comment]
I finally installed eclim works. here is the summary what I did

1. Don't use eclispe Installer to install eclipse.  see issue  https://github.com/ervandew/eclim/issues/485
2. Don't use eclim installer, see issue https://github.com/ervandew/eclim/issues/517, build from the source.
3. When building from the source, don't use ant 1.9.7+,  1.9.6 works.  see issue https://github.com/ervandew/eclim/issues/330

hope it works

**Comment by rayoub** [comment]
Are there any plans to fix this? It appears that unless you build from source, eclim will just not install anymore for those of us not wanting the hassle.

**Comment by rayoub** [comment]
I went back to eclipse neon and eclim 2.6.0 and everything works fine. It appears eclim is not ready for oxygen and it is not necessary for my purposes. My guess is that it is a timing issue that results in accessing a directory while it is not quite ready to be accessed.

**Comment by ervandew** [comment]
I'm closing this out since I just released a new installer for eclim that should solve all the issues related to attempting to use the old gui eclim installer against eclipse installed via their gui installer.
